-- MySQL Script generated by MySQL Workbench
-- Mon Feb 24 08:44:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_degat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_degat` (
  `pk_degat` INT NOT NULL AUTO_INCREMENT,
  `degat` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`pk_degat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_location` (
  `pk_location` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`pk_location`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_boss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_boss` (
  `t_boss` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `hp` INT NOT NULL,
  `def` INT NOT NULL,
  `fk_location` INT NOT NULL,
  PRIMARY KEY (`t_boss`),
  INDEX `fk_t_boss_t_location_idx` (`fk_location` ASC) VISIBLE,
  CONSTRAINT `fk_t_boss_t_location`
    FOREIGN KEY (`fk_location`)
    REFERENCES `mydb`.`t_location` (`pk_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_resistance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_resistance` (
  `pk_resistance` INT NOT NULL AUTO_INCREMENT,
  `resistance` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`pk_resistance`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`t_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`t_utilisateur` (
  `pk_utilisateur` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(30) NOT NULL,
  `pwd` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`pk_utilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tr_boss_resistance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tr_boss_resistance` (
  `fk_boss` INT NOT NULL,
  `fk_resistance` INT NOT NULL,
  INDEX `fk_t_boss_has_t_resistance_t_resistance1_idx` (`fk_resistance` ASC) VISIBLE,
  INDEX `fk_t_boss_has_t_resistance_t_boss1_idx` (`fk_boss` ASC) VISIBLE,
  CONSTRAINT `fk_t_boss_has_t_resistance_t_boss1`
    FOREIGN KEY (`fk_boss`)
    REFERENCES `mydb`.`t_boss` (`t_boss`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_boss_has_t_resistance_t_resistance1`
    FOREIGN KEY (`fk_resistance`)
    REFERENCES `mydb`.`t_resistance` (`pk_resistance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tr_boss_degat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tr_boss_degat` (
  `fk_boss` INT NOT NULL,
  `fk_degat` INT NOT NULL,
  INDEX `fk_t_boss_has_t_degat_t_degat1_idx` (`fk_degat` ASC) VISIBLE,
  INDEX `fk_t_boss_has_t_degat_t_boss1_idx` (`fk_boss` ASC) VISIBLE,
  CONSTRAINT `fk_t_boss_has_t_degat_t_boss1`
    FOREIGN KEY (`fk_boss`)
    REFERENCES `mydb`.`t_boss` (`t_boss`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_boss_has_t_degat_t_degat1`
    FOREIGN KEY (`fk_degat`)
    REFERENCES `mydb`.`t_degat` (`pk_degat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`t_location`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`t_location` (`pk_location`, `location`) VALUES (1, 'Limgrave');
INSERT INTO `mydb`.`t_location` (`pk_location`, `location`) VALUES (2, 'Weeping Peninsula');
INSERT INTO `mydb`.`t_location` (`pk_location`, `location`) VALUES (3, 'Caelid');
INSERT INTO `mydb`.`t_location` (`pk_location`, `location`) VALUES (4, 'Liurnia');
INSERT INTO `mydb`.`t_location` (`pk_location`, `location`) VALUES (5, 'Mt Gelmir');
INSERT INTO `mydb`.`t_location` (`pk_location`, `location`) VALUES (6, 'Altus Plateau');
INSERT INTO `mydb`.`t_location` (`pk_location`, `location`) VALUES (7, 'Leyndell Royal Capital');
INSERT INTO `mydb`.`t_location` (`pk_location`, `location`) VALUES (8, 'Mountaintops of the Giants');
INSERT INTO `mydb`.`t_location` (`pk_location`, `location`) VALUES (9, 'Miquellas Haligtree');
INSERT INTO `mydb`.`t_location` (`pk_location`, `location`) VALUES (10, 'Crumbling Farum Azula');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`t_boss`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`t_boss` (`t_boss`, `nom`, `hp`, `def`, `fk_location`) VALUES (1, 'Grafted Scion', 2000, 105, 1);
INSERT INTO `mydb`.`t_boss` (`t_boss`, `nom`, `hp`, `def`, `fk_location`) VALUES (2, 'Godrick The Grafted', 6080, 105, 1);
INSERT INTO `mydb`.`t_boss` (`t_boss`, `nom`, `hp`, `def`, `fk_location`) VALUES (3, 'Red Wolf Of Radagon', 2204, 107, 4);

COMMIT;

